package monopoly;
import Excepciones.MalFormato.*;
import Excepciones.Ejecucion.*;
import Excepciones.MalUsoComando.*;

public interface Comando {
    void anadirjugador();
    void jugadorInfo();
    void edificar(String nombre);
    void listarJugadores();
    void listarAvatares();
    void listarVenta();
    void listarEdificios() ;
    void listarGrupo(String grupo);
    void lanzarDados() throws AcabarTurno;
    void lanzarDados(String dado1, String dado2) throws LanzarDado, AcabarTurno;
    void lanzarDados(int valor);
    void comprar(String nombre) throws Exception;
    void salirCarcel();
    void acabar() throws AcabarTurno;
    void acabarTurnoForce();
    void descJugador(String nombre);
    void descAvatar(String nombre);
    void descCasilla(String nombre);
    void vender_edificio(String edificio, String nombre, String cantidad) throws VenderSinTener;
    void verTablero();
    void endGame();
    void fortunaManual(float cantidad);
    void cambiarModo();
    void bancarrota();
    void hipotecar(String nombre) throws HipotecaSinTener;
    void deshipotecar(String nombre);
    void avanzar() throws AvanzarSinPoder;
    void verTratos();
    void crearTrato(String[] partes) throws TratoIncompatible;
    void aceptarTrato(String id) throws TratoIncompatible;
    void eliminarTrato(String id);
    void estadisticas(String nombre);
    void estadisticasjuego();
}